### PR TITLE
ezTrans XP translator support

### PR DESCRIPTION
**Pull request by Jiwon-Park**
Implemented support for Japanese-Korean translator ezTrans XP using `ExtProtocolEndpoint`.

It supports Japanese to Korean translation only.

### CODE REVIEW

**Comment by gravydevsupreme** [comment]
Greetings,

Thanks for the PR!

I will probably see if I can get this merged in at the first opportune moment. 

Although I am not entirely sure how I would go about testing it.

**Comment by Jiwon-Park** [comment]
I think you can test with this way

1. Install [ezTrans XP](https://drive.google.com/open?id=0BwAk6oar32L3VXFQX0xWSzNxNHc) (3 days trial)

2. Run installed ezTrans to initialize. (Click `계속` on CD key registration)

3. You can close following ezTrans window.

3. Download [Ehnd](https://github.com/sokcuri/ehnd/releases) and unzip in ezTrans installation directory. (It will replace your `J2KEngine.dll`)

And you are ready to test this code.

**Comment by gravydevsupreme** [comment]
I have now merged the changes into master and confirmed it working. I have made the following changes:
 1. Change the new projects to use the new SDK and removed some oddities that was created in some project files due to an apparent project upgrade.
 2. Changed the ezTrans installation directory lookup to use registry. (the provided implementation would only work for 32-bit applications since ezTrans is always 32-bit, but most unity applications are 64-bit, which would cause it to think ezTrans is placed in a directory that does not exist)
 3. Changed the implementation to use `J2KEngineH.dll` by default, but fallback to `J2KEngine.dll` if not found.

The third point (3) is based on an assumption on my part about how this is supposed to work, but I really don't know so I would like you to confirm that.

**Comment by Jiwon-Park** [comment]
I think your assumption is right. I forgot to write `J2KEngineH.dll` is modified engine file for better translation that another user made. Basically its translation function name and input parameter is equal to `J2KEngine.dll`. Great job.

**Comment by Jiwon-Park** [comment]
You misspelled my nickname in change logs.

**Comment by gravydevsupreme** [comment]
Noted and fixed. :)

**Pull request merged**
